### ISSUE TITLE
MissingMethodException: MethodNotFound

### ISSUE THREAD

**Issue by WhitWaldo** [SoCreate/service-fabric-data-protection#6]
I just tried to install this in a fresh SF app with nothing but a stateless ASP.NET Core service and a stateful service. The stateful service is quite simple, per the docs:

//Cache.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <ServerGarbageCollection>False</ServerGarbageCollection>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <TargetLatestRuntimePatch>False</TargetLatestRuntimePatch>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="6.*" />
    <PackageReference Include="SoCreate.Extensions.Caching.ServiceFabric" Version="3.*" />
  </ItemGroup>

</Project>
```

//Cache.cs
```cs
    public class Cache : DistributedCacheStoreService
    {
        protected override int MaxCacheSizeInMegabytes => 1000;

        public Cache(StatefulServiceContext context)
            : base(context)
        {
        }
    }
```

The client website's base entry point is populated with basic Blazor registrations and:

//ConsumerWeb.cs
```cs
builder.Services.AddDataProtection().PersistKeysToServiceFabricDistributedCache(opt =>
{
    opt.CacheStoreId = new Guid("d508351d-66b6-4775-bee5-de58451fe0ce");
});
```

Nothing fancy going on. I start up the application and open a browser for the website and see the following:

## An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'Void Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Client.FabricTransportServiceRemotingClientFactory..ctor(Microsoft.ServiceFabric.Services.Remoting.FabricTransport.FabricTransportRemotingSettings, Microsoft.ServiceFabric.Services.Remoting.V2.Client.IServiceRemotingCallbackMessageHandler, Microsoft.ServiceFabric.Services.Client.IServicePartitionResolver, System.Collections.Generic.IEnumerable`1<Microsoft.ServiceFabric.Services.Communication.Client.IExceptionHandler>, System.String, Microsoft.ServiceFabric.Services.Remoting.V2.IServiceRemotingMessageSerializationProvider)'.

SoCreate.Extensions.Caching.ServiceFabric.DistributedCacheStoreLocator+<>c.<GetCacheStoreProxy>b__11_1(IServiceRemotingCallbackMessageHandler c)

AggregateException: One or more errors occurred. (Method not found: 'Void Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Client.FabricTransportServiceRemotingClientFactory..ctor(Microsoft.ServiceFabric.Services.Remoting.FabricTransport.FabricTransportRemotingSettings, Microsoft.ServiceFabric.Services.Remoting.V2.Client.IServiceRemotingCallbackMessageHandler, Microsoft.ServiceFabric.Services.Client.IServicePartitionResolver, System.Collections.Generic.IEnumerable`1<Microsoft.ServiceFabric.Services.Communication.Client.IExceptionHandler>, System.String, Microsoft.ServiceFabric.Services.Remoting.V2.IServiceRemotingMessageSerializationProvider)'.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. For more information go to http://aka.ms/dataprotectionwarning
Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(byte[] plaintext)

## And the full stacktrace for you:

System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. For more information go to http://aka.ms/dataprotectionwarning
 ---> System.AggregateException: One or more errors occurred. (Method not found: 'Void Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Client.FabricTransportServiceRemotingClientFactory..ctor(Microsoft.ServiceFabric.Services.Remoting.FabricTransport.FabricTransportRemotingSettings, Microsoft.ServiceFabric.Services.Remoting.V2.Client.IServiceRemotingCallbackMessageHandler, Microsoft.ServiceFabric.Services.Client.IServicePartitionResolver, System.Collections.Generic.IEnumerable`1<Microsoft.ServiceFabric.Services.Communication.Client.IExceptionHandler>, System.String, Microsoft.ServiceFabric.Services.Remoting.V2.IServiceRemotingMessageSerializationProvider)'.)
 ---> System.MissingMethodException: Method not found: 'Void Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Client.FabricTransportServiceRemotingClientFactory..ctor(Microsoft.ServiceFabric.Services.Remoting.FabricTransport.FabricTransportRemotingSettings, Microsoft.ServiceFabric.Services.Remoting.V2.Client.IServiceRemotingCallbackMessageHandler, Microsoft.ServiceFabric.Services.Client.IServicePartitionResolver, System.Collections.Generic.IEnumerable`1<Microsoft.ServiceFabric.Services.Communication.Client.IExceptionHandler>, System.String, Microsoft.ServiceFabric.Services.Remoting.V2.IServiceRemotingMessageSerializationProvider)'.
   at SoCreate.Extensions.Caching.ServiceFabric.DistributedCacheStoreLocator.<>c.<GetCacheStoreProxy>b__11_1(IServiceRemotingCallbackMessageHandler c)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Client.ServiceProxyFactory.CreateServiceRemotingClientFactory(IServiceRemotingCallbackMessageHandler callbackClient)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Client.ServiceProxyFactory.CreateServiceRemotingClientFactory(Type serviceInterfaceType)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Client.ServiceProxyFactory.GetOrCreateServiceRemotingClientFactory(Type serviceInterfaceType)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Client.ServiceProxyFactory.CreateServiceProxy[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName, Type serviceInterfaceType, ServiceProxyGenerator proxyGenerator)
   at Microsoft.ServiceFabric.Services.Remoting.V2.Client.ServiceProxyFactory.CreateServiceProxy[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName)
   at Microsoft.ServiceFabric.Services.Remoting.Client.ServiceProxyFactory.CreateServiceProxy[TServiceInterface](Uri serviceUri, ServicePartitionKey partitionKey, TargetReplicaSelector targetReplicaSelector, String listenerName)
   at SoCreate.Extensions.Caching.ServiceFabric.DistributedCacheStoreLocator.<>c__DisplayClass11_0.<GetCacheStoreProxy>b__0(Guid key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at SoCreate.Extensions.Caching.ServiceFabric.DistributedCacheStoreLocator.GetCacheStoreProxy(String cacheKey)
   at SoCreate.Extensions.Caching.ServiceFabric.ServiceFabricDistributedCache.GetAsync(String key, CancellationToken token)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SoCreate.Extensions.Caching.ServiceFabric.ServiceFabricDistributedCache.Get(String key)
   at SoCreate.AspNetCore.DataProtection.ServiceFabric.ServiceFabricXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.Authentication.SecureDataFormat`1.Protect(TData data)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.WriteNonceCookie(String nonce)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Only difference here is that I'm using a brand new SF project, so it's got the new minimalistic service template for ASP.NET Core on the latest 6.0 SF release. Any guesses why this doesn't work suddenly?

**Comment by WhitWaldo** [comment]
Oh, that's a fun one. Installing the updated `SoCreate.Extensions.Caching.ServiceFabric` 3.0.0 package to the non-cache service fixes the whole thing.
